### PR TITLE
feat: #1042 Allow configure db ConnMaxLifetime & ConnMaxIdleTime

### PR DESCRIPTION
**Pull request by jeswinsimon**
### Purpose or design rationale of this PR

Allow `connMaxLifetime` and `connMaxIdleTime` to be configured for database connections

### feat: #1042 Allow configure db ConnMaxLifetime & ConnMaxIdleTime

Your PR title must follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) (as we are doing squash merge for each PR), so it must start with one of the following [types](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type):

- [ ] build: Changes that affect the build system or external dependencies (example scopes: yarn, eslint, typescript)
- [ ] ci: Changes to our CI configuration files and scripts (example scopes: vercel, github, cypress)
- [ ] docs: Documentation-only changes
- [x] feat: A new feature
- [ ] fix: A bug fix
- [ ] perf: A code change that improves performance
- [ ] refactor: A code change that doesn't fix a bug, or add a feature, or improves performance
- [ ] style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
- [ ] test: Adding missing tests or correcting existing tests

### Deployment tag versioning

Has `tag` in `common/version.go` been updated or have you added `bump-version` label to this PR?

- [x] No, this PR doesn't involve a new deployment, git tag, docker image tag
- [ ] Yes

### Breaking change label

Does this PR have the `breaking-change` label?

- [x] No, this PR is not a breaking change
- [ ] Yes

### CODE REVIEW

**Comment by 0xmountaintop** [comment]
looks great.

do you think we can 
1) make these fields optional (`omitempty`); and
2) have default config value 
so that the marshalling & unmarshalling are compatible with previous codes?

**Comment by jeswinsimon** [comment]
> looks great.
> 
> do you think we can
> 
> 1. make these fields optional (`omitempty`); and
> 2. have default config value
>    so that the marshalling & unmarshalling are compatible with previous codes?

@HAOYUatHZ Done.

**Comment by jeswinsimon** [comment]
@HAOYUatHZ I have fixed the failing test cases.

**Comment by 0xmountaintop** [comment]
looks weird that there are so many contracts diff

I guess it's because the `develop` branch of your fork is left behind?

**Comment by jeswinsimon** [comment]
@HAOYUatHZ The additional file change happened after I rebased to develop. I am closing this PR in favour of https://github.com/scroll-tech/scroll/pull/1207. It has all the changes

**Pull request closed without merging**
