### PR TITLE
fix(test): chain monitor server endpoint conflict

### PR DESCRIPTION
**Pull request by colinlyguo**
### Purpose or design rationale of this PR

Currently, mock chain monitor server's is constant, will conflict when multiple CIs are running in the meantime.

### PR title

Your PR title must follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) (as we are doing squash merge for each PR), so it must start with one of the following [types](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type):

- [x] fix: A bug fix

### Deployment tag versioning

Has `tag` in `common/version.go` been updated or have you added `bump-version` label to this PR?

- [x] No, this PR doesn't involve a new deployment, git tag, docker image tag

### Breaking change label

Does this PR have the `breaking-change` label?

- [x] No, this PR is not a breaking change

### CODE REVIEW

**Review by georgehao — DISMISSED** [review]

**Review by georgehao — APPROVED** [review]

**Review by 0xmountaintop — APPROVED** [review]

**Comment by 0xmountaintop** [comment]
I don't think we need to bump version for this PR?

**Comment by georgehao** [comment]
> I don't think we need to bump version for this PR?

Yeah. Because i modify too much today. I want build a new version rollup to deploy to sepolia. 

And just need upgrade the rollup of sepolia to change to chain_monitor api

**Comment by colinlyguo** [comment]
> I don't think we need to bump version for this PR?

Yeah, btw, I think this PR does not affect any binaries, so we don't need to bump version in this PR.

**Comment by georgehao** [comment]
> > I don't think we need to bump version for this PR?
> 
> Yeah, btw, I think this PR does not affect any binaries, so we don't need to bump version in this PR.

I bump the version. Because I don't want submit a bump version pr. ahh

**Pull request merged**
