### PR TITLE
refactor: use submodules for contracts

### PR DESCRIPTION
**Pull request by zimpha**
### Purpose or design rationale of this PR

This PR remove `contracts` directory and add `scroll-contracts` repo ad submodule.

Q: Why not reuse `contracts` directory for the submodule? 
A: It contains submodules before, changing it to another submodule would lead some problems in git.

### PR title

Your PR title must follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) (as we are doing squash merge for each PR), so it must start with one of the following [types](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type):

- [x] refactor: A code change that doesn't fix a bug, or add a feature, or improves performance

### Deployment tag versioning

Has `tag` in `common/version.go` been updated or have you added `bump-version` label to this PR?

- [x] No, this PR doesn't involve a new deployment, git tag, docker image tag
- [ ] Yes

### Breaking change label

Does this PR have the `breaking-change` label?

- [x] No, this PR is not a breaking change
- [ ] Yes

### CODE REVIEW

**Comment by georgehao** [comment]
How about don't put submoudle to monorepo, also remove `l2geth` submodule @Thegaram @HAOYUatHZ

**Comment by Thegaram** [comment]
> How about don't put submoudle to monorepo, also remove `l2geth` submodule @Thegaram @HAOYUatHZ

Sounds good to me. I'm fine with removing it. But as I recall a few integration tests are using it. (Maybe it's fine to remove those.)

**Comment by zimpha** [comment]
> > How about don't put submoudle to monorepo, also remove `l2geth` submodule @Thegaram @HAOYUatHZ
> 
> Sounds good to me. I'm fine with removing it. But as I recall a few integration tests are using it. (Maybe it's fine to remove those.)

agreed.

**Comment by 0xmountaintop** [comment]
> How about don't put submoudle to monorepo, also remove `l2geth` submodule @Thegaram @HAOYUatHZ

ok

**Comment by colinlyguo** [comment]
Reopen this PR, we will still use codec implementations to check the workflow (mainly hash calculation) in infra components.

These hash checks are minimum requirements for merging new features, it can at least align contract and infra components to some extent.

**Review by colinlyguo — APPROVED** [review]

**Review by georgehao — APPROVED** [review]

**Pull request merged**
