### PR TITLE
fix: override config values use viper

### PR DESCRIPTION
**Pull request by yiweichi**
### Purpose or design rationale of this PR

This PR aims to solve the bug when trying to override private key fields like `gas_oracle_sender_private_key` , `commit_sender_private_key`. 
For now, the way we override config fields is based on the tag of JSON marshaller, but the real tag of those private keys are `json:"-"`, so here I propose to handle it specifically as a private key when the tag is `-`.
Didn't use `Viper` because seems that will  involve quite amount of code changes.

### PR title

Your PR title must follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) (as we are doing squash merge for each PR), so it must start with one of the following [types](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type):

- [x] fix: A bug fix

### Deployment tag versioning

Has `tag` in `common/version.go` been updated or have you added `bump-version` label to this PR?

- [x] Yes

### Breaking change label

Does this PR have the `breaking-change` label?

- [x] No, this PR is not a breaking change

### CODE REVIEW

**Comment by georgehao** [comment]
Suggestion: use `viper` https://github.com/scroll-tech/scroll/pull/1492 to replace the current implementation

**Review by colinlyguo — APPROVED** [review]

**Comment by colinlyguo** [comment]
> Suggestion: use `viper` #1492 to replace the current implementation

looks like the change is significant. @yiweichi what's the major part of code change? e.g. the self-implementing marshaling/unmarshaling private key part?

**Review by colinlyguo — DISMISSED** [review]

**Comment by yiweichi** [comment]
> > Suggestion: use `viper` #1492 to replace the current implementation
> 
> looks like the change is significant. @yiweichi what's the major part of code change? e.g. the self-implementing marshaling/unmarshaling private key part?

Yes, the major part would be marshaling/unmarshaling private key part.

**Comment by colinlyguo** [comment]
> > > Suggestion: use `viper` #1492 to replace the current implementation
> > 
> > 
> > looks like the change is significant. @yiweichi what's the major part of code change? e.g. the self-implementing marshaling/unmarshaling private key part?
> 
> Yes, the major part would be marshaling/unmarshaling private key part.

added a pr to try it. still a bit messy though.

**Review by Thegaram — DISMISSED** [review]

**Review by colinlyguo — APPROVED** [review]

**Review by georgehao — APPROVED** [review]

**Pull request merged**
